server:
  port: 8080
  
spring:
  application:
    name: spring-boot-radis
  radis: 
    host: localhost
    port: 6379
    timeout: 10000
  cache:
    type: radis 
    radis:
     cache-null-values: false
     user-key-prefix: true
     key-prefix: app
     time-to-live: 60000
 
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
        ddl-auto: update

  h2:
    console:
      enabled: true
      path: /h2-console